### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zunichky/tc359_holidays_forms#1]
Nice datepicker! This has what seems to me like some unexpected behavior however. With the datepicker, I choose an exact day, but then am shown holidays for *every* day in that month. Can you update this to either not allow me to choose the day or only show me holidays for that day? 

Ping me here when it's done and I'll take another look.

**Comment by zunichky** [comment]
I updated my page to show only the day that is selected. Should be good now!

**Comment by chrisvfritz** [comment]
:+1: Much better!
